package com.myhebut.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.myhebut.greendao.Notification;

import com.myhebut.greendao.NotificationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig notificationDaoConfig;

    private final NotificationDao notificationDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        notificationDaoConfig = daoConfigMap.get(NotificationDao.class).clone();
        notificationDaoConfig.initIdentityScope(type);

        notificationDao = new NotificationDao(notificationDaoConfig, this);

        registerDao(Notification.class, notificationDao);
    }
    
    public void clear() {
        notificationDaoConfig.getIdentityScope().clear();
    }

    public NotificationDao getNotificationDao() {
        return notificationDao;
    }

}
