package com.myhebut.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "NOTIFICATION".
 */
public class Notification {

    private Long id;
    private int type;
    private int isread;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String outline;
    /** Not-null value. */
    private String content;
    /** Not-null value. */
    private String create_time;

    public Notification() {
    }

    public Notification(Long id) {
        this.id = id;
    }

    public Notification(Long id, int type, int isread, String title, String outline, String content, String create_time) {
        this.id = id;
        this.type = type;
        this.isread = isread;
        this.title = title;
        this.outline = outline;
        this.content = content;
        this.create_time = create_time;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getIsread() {
        return isread;
    }

    public void setIsread(int isread) {
        this.isread = isread;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getOutline() {
        return outline;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setOutline(String outline) {
        this.outline = outline;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    /** Not-null value. */
    public String getCreate_time() {
        return create_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCreate_time(String create_time) {
        this.create_time = create_time;
    }

}
